language: csharp
solution: EDSEditor.sln
mono:
  - 6.10.0

notifications:
  slack:
    rooms:
        - secure: "FId7MhkC2Fq8T9ETn5XrWw1STQusuhR7MbOz/YaCPLAvxvo4pPMyGKVu+1urrbvS9eW+o15xqL0dZow2/JG+6vxPgQIyHBcJT0LYfLROrHC22DhR2oydPO0Y4wejxWwcj4LzAXrI/09zynbX6tWphMM0MVbLRKL+WpJRVhAsCHB2FXHZxF2uT6774J+7dEpY2gtW676ShO4gU7DmD/bEOgasyvDqtpGtM4bxEQJubJr4iaUlxvGlQ8CJyBXfBxcviL5ufMjJxGmuDYHzKu2pxN1v6adfRA53CrgSlb2JIx+ubNx/xGJQN+XeGrnA6aRU15CE/6iC8qZ6CW5FBfcCESp6/JPpVeom3WHbYoXZBQbAOXDuLg+zHxF5N4kwSuZLapOcfIm7wppVlrSbY6cUZ5cNUnbVCfml+1BGC6R1++80wOaBG6g/IkHsbo3ZMtqibutg2BDEYoJeFq0GORySYPp5MTt2+iuKngLjtY4z9q2RWF+0e9/5rcYkUysUT7M0pP9SmKnI3Xvyxl853KY4xH7IiN+hZ4qoAGw4yQKJggPtUka9zihCxnxDyDOKnf6XVcZrPFucW2k2qwwZI9BMX5thNi2sB/3pAcA0kRC7yOGwLWLY21sTObB5QpDKJKeDYK1n9iss+xyIV2OoD7vwTw+sIeFFTTxyWA50AIdtmYU="
  
before_deploy:
- cp $TRAVIS_BUILD_DIR/EDSSharp/bin/Release/EDSSharp.* $TRAVIS_BUILD_DIR/EDSEditorGUI/bin/Release/
- cd $TRAVIS_BUILD_DIR/EDSEditorGUI/bin/Release/
- zip -r $TRAVIS_BUILD_DIR/build/OpenEDSEditor-latest.zip *
- cd $TRAVIS_BUILD_DIR

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  target_branch: gh-pages
  directory: $TRAVIS_BUILD_DIR/build/

  on:
    branch: xdd
    
    
  